version: "3"

services:
  collector:
    build: ./collector
    image: icr/collector
    ports:
      - "3100:3100"
    profiles: [collector]

  collector-db:
    build: ./collector/db
    image: icr/collector-db
    ports:
      - "7331:7331"
    profiles: [collector]

  kathara-base:
    build: ./kathara-base
    image: icr/kathara-base
    profiles: [kathara]

  mitm-arp-spoofing:
    build: ./mitm/arp-spoofing
    image: icr/mitm-arp-spoofing
    cap_add:
      - NET_ADMIN
    profiles: [kali]


  Reconnaissance-arp-scanning:
    build: ./Reconnaissance/arp-scanning
    image: icr/reconnaissance-arp-scanning
    cap_add:
      - NET_ADMIN
    profiles:
      - kali

  Reconnaissance-icmp-scanning:
    build: ./Reconnaissance/ICMP-scanning
    image: icr/reconnaissance-icmp-scanning
    cap_add:
      - NET_ADMIN
    profiles:
      - kali

  Reconnaissance-port-scanning:
    build: ./Reconnaissance/port-scanning
    image: icr/reconnaissance-port-scanning
    cap_add:
      - NET_ADMIN
    profiles:
      - kali

  Reconnaissance-os-fingerprint:
    build: ./Reconnaissance/os-fingerprinting
    image: icr/reconnaissance-os-fingerprint
    cap_add:
      - NET_ADMIN
    profiles:
      - kali

  Reconnaissance-service-enumeration:
    build: ./Reconnaissance/service-enumeration
    image: icr/reconnaissance-service-enumeration
    cap_add:
      - NET_ADMIN
    profiles:
      - kali


  dos-modbustcp-flood:
    build: ./dos/modbustcp-flood
    image: icr/dos-modbustcp-flood
    cap_add:
      - NET_ADMIN
    profiles:
      - kali

  dos-icmp-flood:
    build: ./dos/icmp-flood
    image: icr/dos-icmp-flood
    cap_add:
      - NET_ADMIN
    profiles: [kali]



  dos-syn-flood:
    build: ./dos/syn-flood
    image: icr/dos-syn-flood
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  dos-udp-flood:
    build: ./dos/udp-flood
    image: icr/dos-udp-flood
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  dos-icmp-floodlite:
    build: ./dos/icmp-flood
    image: icr/dos-icmp-floodlite
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  dos-syn-floodlite:
    build: ./dos/syn-flood
    image: icr/dos-syn-floodlite
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  dos-udp-floodlite:
    build: ./dos/udp-flood
    image: icr/dos-udp-floodlite
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  ping-icmp-ping:
    build: ./PING/icmp-ping
    image: icr/ping-icmp-ping
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  ping-syn-ping:
    build: ./PING/syn-ping
    image: icr/ping-syn-ping
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  ping-udp-ping:
    build: ./PING/udp-ping
    image: icr/ping-udp-ping
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  ping-icmp-pinglite:
    build: ./PING/icmp-ping
    image: icr/ping-icmp-pinglite
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  ping-syn-pinglite:
    build: ./PING/syn-ping
    image: icr/ping-syn-pinglite
    cap_add:
      - NET_ADMIN
    profiles: [kali]

  ping-udp-pinglite:
    build: ./PING/udp-ping
    image: icr/ping-udp-pinglite
    cap_add:
      - NET_ADMIN
    profiles: [kali]
  apg:
    build: ./apg
    image: icr/apg

  conveyor:
    build: ./conveyor
    image: icr/conveyor

  laser:
    build: ./laser
    image: icr/laser

  plc:
    build: ./plc
    image: icr/plc

  rejector:
    build: ./rejector
    image: icr/rejector

  scada:
    build: ./scada
    image: icr/scada
  
  

